import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Bus, CarFront, ChevronRight, Package, Ticket } from 'lucide-react';
import { TripSearchForm } from '@/features/trips/components/trip-search-form';
import { news, promotions } from '@/mocks/trips';

const routeGroups = [
  { id: 'from-hcm', city: 'TP. Hồ Chí Minh', image: '/images/route1.jpg', routes: [['Đà Lạt', '300.000đ', '310km - 8 giờ'], ['Cần Thơ', '165.000đ', '170km - 4 giờ'], ['Long Xuyên', '200.000đ', '200km - 6 giờ']] },
  { id: 'from-dalat', city: 'Đà Lạt', image: '/images/route2.jpg', routes: [['TP. Hồ Chí Minh', '300.000đ', '310km - 8 giờ'], ['Đà Nẵng', '350.000đ', '700km - 14 giờ'], ['Cần Thơ', '450.000đ', '450km - 11 giờ']] },
  { id: 'from-danang', city: 'Đà Nẵng', image: '/images/route3.jpg', routes: [['Đà Lạt', '400.000đ', '700km - 14 giờ'], ['TP. Hồ Chí Minh', '500.000đ', '900km - 20 giờ'], ['Nha Trang', '450.000đ', '550km - 10 giờ']] },
];

const ecosystem = [
  { title: 'Xe Hợp Đồng', icon: CarFront, active: false },
  { title: 'Mua vé VexGo', icon: Ticket, active: true },
  { title: 'Giao Hàng', icon: Package, active: false },
  { title: 'Xe Buýt', icon: Bus, active: false },
];

const promotionCards = [promotions[1], promotions[0], promotions[2]];

export default function HomePage() {
  return <div className="bg-[#f5f5f5]">
    <section className="relative flex flex-col items-center bg-[#f5f5f5] pb-12"><div className="relative h-[380px] w-full md:h-[480px]"><div className="absolute inset-0 bg-[url('/images/promo2.jpg')] bg-cover bg-center" /><div className="absolute inset-0 bg-gradient-to-b from-black/60 via-black/20 to-transparent" /><div className="absolute inset-0 flex flex-col items-center justify-center px-4 pt-8 text-center"><h1 className="text-3xl font-black uppercase tracking-wider text-white drop-shadow-lg md:text-5xl lg:text-6xl"><span className="text-accent">VỮNG TIN</span> &amp; PHÁT TRIỂN</h1><p className="mt-4 rounded-full bg-black/20 px-4 py-1.5 text-sm font-bold text-white/90 backdrop-blur-sm md:text-lg">Chất lượng là danh dự - Hàng ngàn chuyến đi mỗi ngày</p></div></div><div className="relative z-10 -mt-32 w-full max-w-[1050px] px-4 sm:px-6 md:-mt-40"><TripSearchForm /></div></section>
    <section className="bg-[#f5f5f5] py-10"><div className="mx-auto max-w-[1050px] px-4 sm:px-6"><h2 className="mb-8 text-center text-xl font-black uppercase text-brand md:text-2xl">Khuyến mãi nổi bật</h2><div className="grid gap-5 sm:grid-cols-3">{promotionCards.map((promo) => <Link href="/trips" key={promo.code} className="group block overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm transition hover:shadow-md"><div className="relative aspect-[16/9]"><Image src={promo.image} alt={promo.title} fill sizes="(max-width: 640px) 100vw, 33vw" className="object-cover transition duration-500 group-hover:scale-105" /></div></Link>)}</div><div className="mt-6 flex justify-center gap-2"><span className="h-2 w-8 rounded-full bg-accent" /><span className="size-2 rounded-full bg-slate-300" /><span className="size-2 rounded-full bg-slate-300" /></div></div></section>
    <section className="bg-white py-12"><div className="mx-auto max-w-[1050px] px-4 sm:px-6"><div className="mb-8 text-center"><h2 className="text-xl font-black uppercase text-brand md:text-2xl">Tuyến phổ biến</h2><p className="mt-1 text-sm font-semibold text-slate-500">Được khách hàng quan tâm</p></div><div className="grid gap-6 md:grid-cols-3">{routeGroups.map((group) => <div key={group.id} className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="relative h-[180px] w-full"><Image src={group.image} alt={group.city} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent" /><div className="absolute bottom-4 left-4 text-white"><p className="text-xs font-semibold">Tuyến xe từ</p><h3 className="text-xl font-black">{group.city}</h3></div></div><div className="p-4">{group.routes.map(([destination, price, detail]) => <Link href="/trips" key={destination} className="flex items-center justify-between rounded-lg border-b border-slate-100 px-2 py-3 transition last:border-0 hover:bg-slate-50"><div><h4 className="text-sm font-bold text-slate-900">{destination}</h4><p className="mt-0.5 text-[11px] text-slate-500">{detail}</p></div><span className="text-sm font-bold text-slate-900">{price}</span></Link>)}</div></div>)}</div></div></section>
    <section className="bg-[#f5f5f5] py-12"><div className="mx-auto max-w-[1050px] px-4 sm:px-6"><div className="mb-8 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div className="flex-1 text-center md:text-left"><h2 className="text-xl font-black uppercase text-brand md:text-2xl">Tin tức mới</h2><p className="mt-1 text-sm font-semibold text-slate-500">Cập nhật những thông tin mới từ VexGo</p></div><Link href="/about" className="flex items-center justify-center gap-1 text-sm font-bold text-accent transition hover:underline md:justify-end">Xem tất cả <ArrowRight className="size-4" /></Link></div><div className="grid gap-6 sm:grid-cols-3">{news.map((item) => <Link href="/about" key={item.title} className="group flex h-full flex-col overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm transition hover:shadow-md"><div className="relative aspect-[16/9] overflow-hidden"><Image src={item.image} alt={item.title} fill sizes="(max-width: 640px) 100vw, 33vw" className="object-cover transition duration-300 group-hover:scale-105" /></div><div className="flex flex-1 flex-col justify-between p-4"><h3 className="line-clamp-2 text-sm font-black uppercase text-slate-900 transition group-hover:text-accent">{item.title}</h3><div className="mt-4 flex items-center justify-between"><span className="text-xs font-medium text-slate-500">{item.date}</span><span className="flex items-center gap-0.5 text-xs font-bold text-accent">Chi tiết <ChevronRight className="size-3" /></span></div></div></Link>)}</div><div className="mt-8 flex justify-center gap-2"><span className="h-2 w-8 rounded-full bg-accent" /><span className="size-2 rounded-full bg-slate-300" /><span className="size-2 rounded-full bg-slate-300" /></div></div></section>
    <section className="bg-white py-12"><div className="mx-auto max-w-[1050px] px-4 sm:px-6"><div className="mb-10 text-center"><h2 className="text-xl font-black uppercase text-brand md:text-2xl">Kết nối hệ sinh thái VexGo</h2><p className="mx-auto mt-2 max-w-xl text-sm font-semibold text-slate-500">Kết nối đa dạng hệ sinh thái VexGo qua một nền tảng: mua vé xe khách, xe buýt, xe hợp đồng, giao hàng...</p></div><div className="flex flex-wrap justify-center gap-6 sm:gap-12 md:gap-20">{ecosystem.map((item) => { const Icon = item.icon; return <Link href={item.active ? '/trips' : '/about'} key={item.title} className="group flex flex-col items-center gap-3"><span className={`flex size-24 items-center justify-center rounded-full transition ${item.active ? 'bg-orange-50 text-accent ring-2 ring-orange-100' : 'border border-slate-100 bg-slate-50 text-slate-400 group-hover:bg-orange-50 group-hover:text-accent'}`}><Icon className="size-8" /></span><span className={`text-base font-bold ${item.active ? 'text-accent' : 'text-slate-600 group-hover:text-accent'}`}>{item.title}</span></Link>; })}</div></div></section>
  </div>;
}
