'use client';

import { useState } from 'react';
import { AccountSidebar } from '@/features/account/components/account-sidebar';
import { Button } from '@/components/ui/button';

export default function AccountProfilePage() {
  const [saved, setSaved] = useState(false);
  return <div className="bg-slate-50"><div className="mx-auto grid max-w-7xl gap-6 px-4 py-10 sm:px-6 md:grid-cols-[240px_1fr] lg:px-8"><AccountSidebar /><section className="rounded-3xl border border-border bg-background p-5 shadow-sm sm:p-8"><p className="text-xs font-black uppercase tracking-[0.18em] text-accent">Tài khoản</p><h1 className="mt-2 text-2xl font-black">Thông tin cá nhân</h1><p className="mt-2 text-sm text-muted-foreground">Cập nhật thông tin để đặt vé nhanh hơn.</p><form className="mt-8 grid gap-5 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); setSaved(true); }}><label className="space-y-2"><span className="text-sm font-bold">Họ và tên</span><input defaultValue="Nguyễn Văn Hùng" className="h-12 w-full rounded-xl border border-input px-4 outline-none focus:border-primary" /></label><label className="space-y-2"><span className="text-sm font-bold">Số điện thoại</span><input defaultValue="0912 345 678" className="h-12 w-full rounded-xl border border-input px-4 outline-none focus:border-primary" /></label><label className="space-y-2"><span className="text-sm font-bold">Email</span><input type="email" defaultValue="hung@example.com" className="h-12 w-full rounded-xl border border-input px-4 outline-none focus:border-primary" /></label><label className="space-y-2"><span className="text-sm font-bold">Ngày sinh</span><input type="date" defaultValue="1990-01-01" className="h-12 w-full rounded-xl border border-input px-4 outline-none focus:border-primary" /></label><label className="space-y-2 sm:col-span-2"><span className="text-sm font-bold">Địa chỉ</span><input placeholder="Nhập địa chỉ" className="h-12 w-full rounded-xl border border-input px-4 outline-none focus:border-primary" /></label>{saved ? <p className="rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-700 sm:col-span-2">Đã lưu thông tin demo.</p> : null}<Button variant="accent" className="sm:w-fit">Lưu thay đổi</Button></form></section></div></div>;
}
