import Link from 'next/link';
import { Clock3, MapPin, ShieldCheck, Star } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { SeatPicker } from '@/features/booking/components/seat-picker';
import { formatCompactCurrency } from '@/lib/format';
import type { Trip } from '@/types/customer';

export function TripDetail({ trip }: { trip: Trip }) {
  return <section className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><Link href="/trips" className="mb-6 inline-flex items-center gap-2 text-sm font-bold text-muted-foreground hover:text-primary">← Quay lại danh sách</Link><div className="grid gap-6 lg:grid-cols-[1.35fr_0.65fr]"><div className="space-y-6"><div className="overflow-hidden rounded-3xl border border-border bg-background shadow-sm"><div className="relative h-52 sm:h-64"><img src={trip.image} alt={`${trip.origin} đến ${trip.destination}`} className="size-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-slate-950/80 to-transparent" /><div className="absolute bottom-5 left-5 text-white sm:left-8"><Badge tone="green">Đang mở bán</Badge><h1 className="mt-3 text-3xl font-black sm:text-4xl">{trip.origin} → {trip.destination}</h1><p className="mt-1 font-semibold text-white/80">{trip.operator} · {trip.vehicleType}</p></div></div><div className="grid gap-4 p-5 sm:grid-cols-3 sm:p-8"><div><p className="text-xs font-bold uppercase text-muted-foreground">Khởi hành</p><p className="mt-1 text-xl font-black">{trip.departureTime}</p><p className="text-sm text-muted-foreground">{trip.origin}</p></div><div><p className="text-xs font-bold uppercase text-muted-foreground">Thời lượng</p><p className="mt-1 flex items-center gap-2 text-xl font-black"><Clock3 size={18} className="text-primary" /> {trip.duration}</p></div><div><p className="text-xs font-bold uppercase text-muted-foreground">Đến nơi</p><p className="mt-1 text-xl font-black">{trip.arrivalTime}</p><p className="text-sm text-muted-foreground">{trip.destination}</p></div></div></div><SeatPicker trip={trip} /></div><aside className="space-y-4"><div className="rounded-2xl border border-border bg-background p-5 shadow-sm"><p className="text-sm font-bold text-muted-foreground">Giá vé từ</p><p className="mt-1 text-3xl font-black text-primary">{formatCompactCurrency(trip.price)}</p><div className="mt-5 space-y-3 border-t border-border pt-5 text-sm font-semibold text-muted-foreground"><p className="flex items-center gap-2"><MapPin size={16} className="text-primary" /> Điểm đón: {trip.origin}</p><p className="flex items-center gap-2"><MapPin size={16} className="text-accent" /> Điểm trả: {trip.destination}</p><p className="flex items-center gap-2"><Star size={16} className="fill-amber-400 text-amber-400" /> Đánh giá {trip.rating}/5</p><p className="flex items-center gap-2"><ShieldCheck size={16} className="text-emerald-600" /> Đổi/hủy theo chính sách backend</p></div></div><div className="rounded-2xl border border-border bg-primary p-5 text-primary-foreground"><h2 className="font-black">Tiện ích trên xe</h2><div className="mt-4 flex flex-wrap gap-2">{trip.amenities.map((item) => <span className="rounded-full bg-white/15 px-3 py-1.5 text-xs font-bold" key={item}>{item}</span>)}</div></div></aside></div></section>;
}
