'use client';

import { useState } from 'react';
import { Clock3, Mail, MapPin, MessageCircle, Phone, Send } from 'lucide-react';
import { Button } from '@/components/ui/button';

export default function ContactPage() {
  const [sent, setSent] = useState(false);
  return <div className="bg-slate-50"><section className="mx-auto max-w-6xl px-4 py-12 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="text-xs font-black uppercase tracking-[0.2em] text-accent">Trung tâm hỗ trợ</p><h1 className="mt-3 text-4xl font-black">Chúng tôi có thể giúp gì cho bạn?</h1><p className="mt-4 text-sm leading-7 text-muted-foreground">Gửi câu hỏi cho VexGo hoặc chọn kênh liên hệ phù hợp với nhu cầu của bạn.</p></div><div className="mt-10 grid gap-6 lg:grid-cols-[0.75fr_1.25fr]"><div className="space-y-4">{[{ icon: Phone, label: 'Hotline', value: '1900 6789' }, { icon: Mail, label: 'Email', value: 'support@vexgo.vn' }, { icon: Clock3, label: 'Thời gian hỗ trợ', value: '08:00 – 22:00 mỗi ngày' }, { icon: MapPin, label: 'Trung tâm vận hành', value: 'TP. Hồ Chí Minh' }].map((item) => <div className="flex gap-4 rounded-2xl border border-border bg-background p-5" key={item.label}><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><item.icon size={20} /></span><div><p className="text-xs font-bold text-muted-foreground">{item.label}</p><p className="mt-1 font-black">{item.value}</p></div></div>)}</div><form className="rounded-3xl border border-border bg-background p-5 shadow-sm sm:p-8" onSubmit={(event) => { event.preventDefault(); setSent(true); }}><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-accent/10 text-accent"><MessageCircle size={20} /></span><div><h2 className="font-black">Gửi yêu cầu hỗ trợ</h2><p className="text-xs text-muted-foreground">Phản hồi demo, chưa gửi API.</p></div></div><div className="mt-7 grid gap-4 sm:grid-cols-2"><input required placeholder="Họ và tên" className="h-12 rounded-xl border border-input px-4 text-sm outline-none focus:border-primary" /><input required type="email" placeholder="Email" className="h-12 rounded-xl border border-input px-4 text-sm outline-none focus:border-primary" /><input placeholder="Chủ đề" className="h-12 rounded-xl border border-input px-4 text-sm outline-none focus:border-primary sm:col-span-2" /><textarea required rows={5} placeholder="Nội dung cần hỗ trợ" className="resize-none rounded-xl border border-input p-4 text-sm outline-none focus:border-primary sm:col-span-2" /></div>{sent ? <p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-700">Đã ghi nhận yêu cầu demo.</p> : null}<Button variant="accent" className="mt-5"><Send size={16} /> Gửi yêu cầu</Button></form></div></section></div>;
}
