// /src/modules/client/my-posts/models/my-posts.mock.ts
import type { MyPostItem } from './my-posts.model';

export const MOCK_USER_POSTS: MyPostItem[] = [
  {
    id: 'TICKET-1080',
    title: 'TP. Hồ Chí Minh đi Đà Lạt - Limousine 22 phòng',
    needType: 'BUY',
    propertyType: 'Limousine giường phòng',
    location: 'Bến xe Miền Đông mới - Bến xe Đà Lạt',
    priceRange: '420.000 VNĐ',
    areaRange: 'Ghế A05',
    createdAt: '16/09/2026',
    updatedAt: '16/09/2026',
    status: 'APPROVED',
    description:
      'Vé đã thanh toán qua VNPAY. Mã QR BW1080-A05. Hệ thống sẽ nhắc lịch trước giờ khởi hành 2 tiếng.',
    contactName: 'Nguyễn Văn Hùng',
    contactPhone: '0912.345.678',
    viewsCount: 1,
  },
  {
    id: 'TICKET-1082',
    title: 'TP. Hồ Chí Minh đi Nha Trang - Giường nằm 34 chỗ',
    needType: 'BUY',
    propertyType: 'Giường nằm',
    location: 'Quận 1, TP. Hồ Chí Minh - Trung tâm Nha Trang',
    priceRange: '320.000 VNĐ',
    areaRange: 'Chờ chọn ghế',
    createdAt: '16/09/2026',
    status: 'PENDING',
    description:
      'Đơn đặt vé đang chờ thanh toán. Ghế sẽ chỉ được giữ trong 10 phút sau khi chọn trên sơ đồ.',
    contactName: 'Nguyễn Văn Hùng',
    contactPhone: '0912.345.678',
    viewsCount: 0,
  },
  {
    id: 'CARGO-1079',
    title: 'Gửi hàng TP. Hồ Chí Minh đi Cần Thơ',
    needType: 'RENT',
    propertyType: 'Gửi hàng hóa',
    location: 'Bến xe Miền Tây - Ninh Kiều, Cần Thơ',
    priceRange: '180.000 VNĐ',
    areaRange: '12 kg',
    createdAt: '15/09/2026',
    status: 'COMPLETED',
    description:
      'Vận đơn đã giao thành công. Người nhận đã xác nhận lúc 18:30 ngày 15/09/2026.',
    contactName: 'Nguyễn Văn Hùng',
    contactPhone: '0912.345.678',
    viewsCount: 3,
  },
  {
    id: 'TICKET-1072',
    title: 'Đà Nẵng đi Huế - Ghế ngồi chất lượng cao',
    needType: 'BUY',
    propertyType: 'Ghế ngồi',
    location: 'Bến xe Trung tâm Đà Nẵng - Bến xe phía Nam Huế',
    priceRange: '150.000 VNĐ',
    areaRange: 'Ghế B12',
    createdAt: '14/09/2026',
    updatedAt: '14/09/2026',
    status: 'HIDDEN',
    description:
      'Vé đã hủy trước giờ khởi hành hơn 3 giờ. Số tiền hoàn lại phụ thuộc quy trình ngân hàng/cổng thanh toán.',
    contactName: 'Nguyễn Văn Hùng',
    contactPhone: '0912.345.678',
    viewsCount: 1,
  },
  {
    id: 'TICKET-1065',
    title: 'TP. Hồ Chí Minh đi Vũng Tàu - Limousine 9 chỗ',
    needType: 'BUY',
    propertyType: 'Limousine',
    location: 'Quận 1, TP. Hồ Chí Minh - Trung tâm Vũng Tàu',
    priceRange: '220.000 VNĐ',
    areaRange: 'Ghế L03',
    createdAt: '12/09/2026',
    updatedAt: '12/09/2026',
    status: 'EXPIRED',
    description:
      'Đơn giữ chỗ đã quá thời gian thanh toán nên hệ thống tự động mở lại ghế cho khách khác.',
    contactName: 'Nguyễn Văn Hùng',
    contactPhone: '0912.345.678',
    viewsCount: 0,
  },
  {
    id: 'CARGO-1088',
    title: 'Gửi hồ sơ Hà Nội đi Đà Nẵng',
    needType: 'RENT',
    propertyType: 'Gửi hàng hóa',
    location: 'Bến xe Nước Ngầm - Bến xe Trung tâm Đà Nẵng',
    priceRange: '95.000 VNĐ',
    areaRange: '1.5 kg',
    createdAt: '16/09/2026',
    status: 'DRAFT',
    description:
      'Bản nháp vận đơn. Cần bổ sung thông tin người nhận trước khi thanh toán.',
    contactName: 'Nguyễn Văn Hùng',
    contactPhone: '0912.345.678',
    viewsCount: 0,
  },
  {
    id: 'TICKET-1091',
    title: 'Hà Nội đi Đà Nẵng - Limousine VIP',
    needType: 'BUY',
    propertyType: 'Limousine VIP',
    location: 'Bến xe Nước Ngầm - Bến xe Trung tâm Đà Nẵng',
    priceRange: '680.000 VNĐ',
    areaRange: 'Ghế VIP-02',
    createdAt: '15/09/2026',
    status: 'REJECTED',
    rejectReason:
      'Giao dịch thanh toán thất bại hoặc hết thời gian chờ. Vui lòng thực hiện thanh toán lại.',
    description:
      'Đơn đặt vé chưa được phát hành do cổng thanh toán trả về trạng thái thất bại.',
    contactName: 'Nguyễn Văn Hùng',
    contactPhone: '0912.345.678',
    viewsCount: 0,
  },
];
