'use client';

import { useState } from 'react';
import { Bot, MessageCircle, Send, X } from 'lucide-react';
import { Button } from '@/components/ui/button';

export function SupportWidget() {
  const [open, setOpen] = useState(false);
  return <>{open ? <div className="fixed bottom-24 right-6 z-50 flex h-[min(540px,80vh)] w-[360px] max-w-[calc(100vw-3rem)] flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl"><div className="flex h-16 shrink-0 items-center justify-between bg-brand px-4 text-white"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-white/20"><Bot className="size-6" /></span><div><p className="text-sm font-bold">Trợ lý VexGo</p><p className="text-[10px] text-white/80">Trả lời tự động · Luôn trực tuyến</p></div></div><button type="button" onClick={() => setOpen(false)} aria-label="Đóng hỗ trợ"><X className="size-5" /></button></div><div className="flex-1 bg-slate-50 p-4"><div className="flex gap-3"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-brand/10 text-brand"><Bot className="size-4" /></span><div className="rounded-2xl rounded-tl-sm border border-slate-100 bg-white p-3 text-sm text-slate-700 shadow-sm">Xin chào! Bạn cần hỗ trợ tìm chuyến, vé hay gửi hàng?</div></div></div><div className="shrink-0 border-t border-slate-100 bg-white p-3"><div className="flex gap-2"><input className="h-11 min-w-0 flex-1 rounded-xl border border-slate-200 bg-slate-50 px-4 text-sm outline-none focus:border-brand focus:bg-white" placeholder="Nhập câu hỏi của bạn..." /><Button variant="primary" className="size-11 min-h-11 shrink-0 px-0"><Send className="size-5" /></Button></div></div></div> : null}{!open ? <button type="button" onClick={() => setOpen(true)} className="group fixed bottom-6 right-6 z-40 grid size-14 place-items-center rounded-full bg-brand text-white shadow-lg transition hover:scale-105 hover:bg-brand-hover" aria-label="Mở hỗ trợ"><MessageCircle className="size-6" /><span className="absolute right-full mr-4 whitespace-nowrap rounded-lg bg-slate-800 px-3 py-1.5 text-xs text-white opacity-0 transition-opacity group-hover:opacity-100">Chat hỗ trợ</span><span className="absolute right-0 top-0 size-3.5 rounded-full border-2 border-white bg-rose-500" /></button> : null}</>;
}
